# Generated by Django 3.1.7 on 2021-06-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response',
            field=models.TextField(default=''),
        ),
    ]
